spring: 
  application: 
    name: hp
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
mybatis: 
  type-aliases-package: cn.hp.dao.model
  mapper-locations: classpath*:mybatis/*.xml  
