server:
  context-path: /hp
  port: 8082
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: B2oDDwxU00sNf7FvXdrg3JuQ+NlKbQ2hSCp37cfJAiyxlnqAzZyd/U4EFbv+K8f27Q1aPNEi7R+JzlW65vgG5w==
    druid:
      maxActive: 100
      initialSize: 1
      minIdle: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      validationQuery: SELECT 'x' from dual
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 900000
      filters: config,stat,wall,slf4j
      filter.stat.db-type: mysql
      filter.stat.merge-sql: true
      filter.stat.slow-sql-millis: 1000
      filter.stat.log-slow-sql: true
      filter.log4j.connection-log-enabled: true
mybatis:
  type-aliases-package: cn.hp.dao.model
  mapper-locations: classpath*:mybatis/*.xml  
redis:
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 3000
    pool:
      max-active: 50
      max-idle: 10
      max-wait: 5 
#配置区域 ,https://hz.lianjia.com/ershoufang/xihu,https://hz.lianjia.com/ershoufang/xiaoshan
spider-list: https://hz.lianjia.com/ershoufang
#模式 01-httpclient全自动 02-httpclient列表页 03-httpclient详情页 04-当日异常url重爬 
#httpclient代理 同上 11-全自动 ...
#21-webmagic爬取 
start-mode: "21"
#测试代理
spider-ip-url: https://hz.fang.lianjia.com/loupan
#线程数
spider-thread-size: 3
#休眠时间
spider-thread-sleep-time: 500
#定时任务配置开关 0-关 1-开
quartz-mode: 0
#定时任务配置时间
quartz-schedule: 0 32 15 29/3 * ?